main:
  - name: Home
    url: '/'
    weight: 10
  - name: Blog
    url: /blog/
    weight: 20
#  - name: Talks
#    url: /talks/
#    weight: 30
#  - name: Events
#    url: /events/
#    weight: 40
  - name: DJ Mixes
    url: https://podcasts.apple.com/fr/podcast/dj-dadoo-net-mixes/id505824965
    weight: 80
  - name: About me
    url: /authors/david-pilato/
    weight: 90
